<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper(\Magento\Search\Helper\Data::class);
?>
<div class="search-box-area">
    <div id="searchx" class="fade">
        <a href="#" class="close-btn" id="close-search">
            <em class="fa fa-times"></em>
        </a>
        <div id="searchbox">
            <form class="form minisearch" id="search_mini_form" action="<?= $block->escapeUrl($helper->getResultUrl()) ?>" method="get">
                <input id="search"
                       data-mage-init='{"quickSearch":{
                                        "formSelector":"#search_mini_form",
                                        "url":"<?= $block->escapeUrl($helper->getSuggestUrl())?>",
                                        "destinationSelector":"#search_autocomplete",
                                        "minSearchLength":"<?= $block->escapeHtml($helper->getMinQueryLength()) ?>"}
                                   }'
                       type="text"
                       name="<?= $block->escapeHtmlAttr($helper->getQueryParamName()) ?>"
                       value="<?= $block->escapeHtmlAttr($helper->getEscapedQueryText()) ?>"
                       placeholder="<?= $block->escapeHtmlAttr(__('Search entire store here...')) ?>"
                       class="input-text"
                       maxlength="<?= $block->escapeHtmlAttr($helper->getMaxQueryLength()) ?>"
                       role="combobox"
                       aria-haspopup="false"
                       aria-autocomplete="both"
                       autocomplete="off"
                       aria-expanded="false"/>
                <button type="submit"
                        title="<?= $block->escapeHtmlAttr(__('Search')) ?>"
                        class="action search"
                        aria-label="Search"
                >
                    <span><?= $block->escapeHtml(__('Search')) ?></span>
                </button>
            </form>
        </div>
    </div>
    <div class="search-icon-area">
        <a href='#searchx'>
            <i class="fa fa-search"></i>
        </a>
    </div>
</div>

<script>
    require(["jquery"], function($){

        $.fn.backgroundMove=function(options){
            var defaults={
                    movementStrength:'50'
                },
                options=$.extend(defaults,options);

            var $this = $(this);

            var movementStrength = options.movementStrength;
            var height = movementStrength / $(window).height();
            var width = movementStrength / $(window).width();
            $this.mousemove(function(e){
                var pageX = e.pageX - ($(window).width() / 2);
                var pageY = e.pageY - ($(window).height() / 2);
                var newvalueX = width * pageX * -1 - 25;
                var newvalueY = height * pageY * -1 - 50;
                $this.css("background-position", newvalueX+"px     "+newvalueY+"px");
            });

        }
    });

</script>
