<div class="col-xl-3 col-lg-3 col-md-3 col-sm-6">
    <div class="footer-heading">
        <h3>Latest works</h3>
    </div>
    <div class="footer-content">
        <ul>
            <li><a href="">sparkel</a></li>
            <li><a href="">getparts</a></li>
            <li><a href="">youtuber</a></li>
            <li><a href="">smartco</a></li>
            <li><a href="">petcare</a></li>
        </ul>
    </div>
</div>