<div class="col-xl-3 col-lg-3 col-md-3 col-sm-6">
    <div class="footer-logo">
        <a href="#">
            <img src="<?php echo $block->getViewFileUrl('imgs/footer-logo.png')?>" alt="">
        </a>
        <p> We have bothh premium and free website templates. Build your professional website with us.</p>
    </div>
    <!--footer social-->
    <div class="social">
        <ul>
            <li><a class="footer-socials" href="#"><i class="fab fa-facebook"></i></a></li>
            <li><a class="footer-socials" href="#"><i class="fab fa-instagram"></i></a></li>
            <li><a class="footer-socials" href="#"><i class="fab fa-twitter"></i></a></li>
            <li><a class="footer-socials" href="#"><i class="fab fa-youtube"></i></a></li>
        </ul>
    </div>
</div>