
    <div class="main-menu f-right">
        <nav id="mobile-menu">
            <ul>
                <li>
                    <a class="current" href="index.html">home</a>
                </li>
                <li>
                    <a href="about-us.html">about</a>
                </li>
                <li>
                    <a href="team.html">team</a>
                </li>
                <!-- dropdown menu-area-->
                <li>
                    <a href="#" onclick="return false">pages <i class="fas fa-angle-down"></i>
                    </a>
                    <ul class="dropdown">
                        <li><a href="about-us.html">about us</a></li>
                        <li><a href="portfolio.html">portfolio</a></li>
                        <li><a href="portfolio2.html">portfolio two</a></li>
                        <li><a href="single-portfolio.html">single portfolio</a></li>
                        <li><a href="blog.html">blog page</a></li>
                        <li><a href="single-blog.html">single blog</a></li>
                        <li><a href="single-blog2.html">single blog two</a></li>
                        <li><a href="team.html">our team</a></li>
                        <li><a href="contact.html">contact us</a></li>
                        <li><a href="404.html">404 Page</a></li>
                    </ul>
                </li>
                <li>
                    <a href="contact.html">contact</a>
                </li>
            </ul>
        </nav>
    </div>
