<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>

<div class="col-xl-2 col-lg-3 col-md-3">
    <div class="logo-area">
        <a href="<?= $block->getUrl('') ?>" title="<?= /* @escapeNotVerified */ $storeName ?>">
            <img src="<?= /* @escapeNotVerified */ $block->getLogoSrc() ?>"
                 title="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
                 alt="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
            />
        </a>
    </div>
</div>