<div class="demo">
    <div class="item">Tem1</div>
    <div class="item">Tem2</div>
    <div class="item">Tem3</div>
    <div class="item">tem4</div>
    <div class="item">Tem5</div>
</div>
<script>
    require([
        'jquery',
        'slickCarousel'
    ],function ($) {
        $.('.demo').slick({
            infinite: true,
            slidesToShow: 3,
            slidesToScroll: 3
        });
    });
</script>